plugins {
    id 'com.android.application'
}

android {
    namespace 'app.onepve.geelyconsole'
    compileSdk 34

    defaultConfig {
        applicationId "app.onepve.geelyconsole"
        minSdk 28
        targetSdk 28
        versionCode 7029
        versionName "1.2.9"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildFeatures {
        buildConfig true
    }

    signingConfigs {
        release {
            storeFile file("release.keystore")
            storePassword System.getenv("KEYSTORE_PASSWORD") ?: "onepve123"
            keyAlias System.getenv("KEY_ALIAS") ?: "onepve"
            keyPassword System.getenv("KEY_PASSWORD") ?: "onepve123"
            enableV1Signing = true
            enableV2Signing = true
            enableV3Signing = true
            enableV4Signing = false
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            signingConfig signingConfigs.release
        }
    }

    lint {
        abortOnError false
        checkReleaseBuilds false
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    aaptOptions {
        noCompress 'mp3', 'wav', 'ogg', 'xtz'
    }
}

dependencies {
}
